AWSTemplateFormatVersion: '2010-09-09'
Description: Lambda Container

Parameters:
  FunctionName:
    Type: String
    Default: banknotebrazil
  ImageUri:
    Description: Path ECR
    Type: String
    Default: 000326655062.dkr.ecr.sa-east-1.amazonaws.com/banknotebrazil:latest

Resources:
  Function:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Ref FunctionName
      Role: !GetAtt Role.Arn
      PackageType: Image
      Code:
        ImageUri: !Ref ImageUri
      MemorySize: 5000
      Timeout: 300

  Role:
    Type: AWS::IAM::Role
    Properties:
      RoleName: banknotebrazil-lambda-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: discovery-lambda-policy
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: 
                  - "cloudformation:DescribeChangeSet"
                  - "cloudformation:DescribeStackResources"
                  - "cloudformation:DescribeStacks"
                  - "cloudformation:GetTemplate"
                  - "cloudformation:ListStackResources"
                  - "cloudwatch:*"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeVpcs"
                  - "ecr:*"
                  - "events:*"
                  - "iam:GetPolicy"
                  - "iam:GetPolicyVersion"
                  - "iam:GetRole"
                  - "iam:GetRolePolicy"
                  - "iam:ListAttachedRolePolicies"
                  - "iam:ListRolePolicies"
                  - "iam:ListRoles"
                  - "iam:PassRole"
                  - "kms:ListAliases"
                  - "lambda:*"
                  - "logs:*"
                  - "tag:GetResources"
                Resource: '*'
      MaxSessionDuration: 3600 