name: Model Performance

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f app/requirements.txt ]; then pip install -r app/requirements.txt; fi
    - name: Download validation set
      run: |
        # script to download validation
        bash app/src/data/download_validation.sh     
    - name: Gerenate Report
      run: |
        # script to download validation
        python app/src/modeling/evaluate_model.py > app/results/results.txt
    - uses: actions/upload-artifact@v1
      with:
        name: results
        path: app/results
    - uses: actions/download-artifact@v1
      with:
        name: results
    - name: comment PR
      uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: results/results.txt