name: Model Performance

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Download validation set
      run: |
        # script to download validation
        bash app/src/data/download_validation.sh     
    - name: Gerenate Report
      run: |
        # script to download validation
        python app/src/modeling/evaluate_model.py > app/output/results.txt
    - uses: actions/upload-artifact@v1
      with:
        name: results
        path: app/output
    - uses: actions/download-artifact@v1
      with:
        name: results
    - name: comment PR
      uses: machine-learning-apps/pr-comment@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: results/results.txt